name: iboxnav
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  flutter_secure_storage: ^8.0.0
  skeletons: ^0.0.3
  intl: ^0.18.0
  xml: ^6.3.0
  dio: ^5.3.0
  dropdown_button2: ^2.3.6
  font_awesome_flutter: ^10.5.0
  google_maps_flutter: ^2.4.0
  floating_pullup_card: ^1.2.0
  animations: ^2.0.7
  fluttertoast: ^8.2.2
  responsive_sizer: ^3.2.0
  url_launcher: ^6.1.12
  data_table_2: ^2.5.6
  vector_math: ^2.1.4
  loader_overlay: ^2.3.0
  flutter_animarker: ^3.2.0
  flutter_native_splash: ^2.3.1
  bottom_sheet_bar: ^2.3.9
  pausable_timer: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/data/map_light.json
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBlack.ttf
          weight: 900
        - asset: assets/fonts/NunitoRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoMedium.ttf
          weight: 500

flutter_native_splash:
  color: "#0B264D"
  image: "assets/images/iboxnav_logo.png"
